# Generated by Django 3.2.12 on 2023-01-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.TextField(max_length=300)),
                ('land', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('emergency', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
            ],
        ),
    ]
