# Generated by Django 3.2.12 on 2023-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230113_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emergency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='land',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
