# Generated by Django 3.2.12 on 2023-01-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
